project:
  type: website

website:
  title: "Kwanhee Yoon"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: projects
      - href: courses.qmd
        text: Courses

  page-footer:
    right: "&copy; 2025, Kwanhee Yoon"      
  
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    math: true       
    
    

execute:
  freeze: auto

